name: Build Check - .NET Framework MVC

on:
  push:
    branches:
      - main   # Or your active branch
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1

    - name: Restore NuGet packages
      run: nuget restore PhysioWeb.sln

    - name: Build the solution
      shell: cmd
      run: |
        "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\MSBuild.exe" PhysioWeb.sln /p:Configuration=Release /verbosity:minimal
